### ISSUE TITLE
Rehacer todos los diagramas corrigiendo los fallos.

### ISSUE THREAD

**Issue by Alejandrotr22** [Gavila25/ProyectoRecetas#68]
- Corregir los fallos del Diagrama de Casos de Uso #5 #41 #39 
 #48

    - [x] Corrección general del Diagrama #51
    - [x] Corregir Seguir Pedido #52
    - [x] Corregir Pedir a domicilio #53
    - [x] Corregir GPS #54
    - [x] Corregir Repartidor #55
    - [x] Corregir Añadir productos #56
 
- Corregir los fallos del Diagrama de Clases #12 #42
 #49

    - [x] Corregir la Clase de SuperMercado #60
    - [x] Corregir la Clase de Restaurantes #61
    - [x] Corregir la Clase de Usuario #62
    - [x] Corregir la Clase de Cesta #63
    - [x] Corregir la Clase de Ingredientes #64
    - [x] Corregir la Clase de Busquedas #65
    - [x] Corregir la Clase de Recetas #66
    - [x] Mantener continuidad con el diagrama de Entidad-Relacion #67

- Corregir los fallos del Diagrama Entidad Relacion #16 #43
#50

    - [x] Corrección general del Diagrama #57
    - [x] Corregir relaciones #58
    - [x] Mantener continuidad con el diagrama de clases #59
